---
title: "PCA"
author: "Chien Lin"
date: "2025-07-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load required library
library("FactoMineR")
#install.packages("ggcorrplot")
library(ggcorrplot)
#install.packages("corrr")
library('corrr')
library(factoextra)
```

## Prepare dataset

```{r}
# remove irrelevant columns
df4 <- df4[, -c(1,2,4,5,6,7,8,10,15,18,19,22)]
```

```{r}
# gather basic information about data set
str(df4)
summary(df4)
```

```{r}
# number of nas
any(is.na(df4))
```

```{r}
# Convert the datetime column to POSIXct
df4$Date <- mdy_hms(df4$Date)

# Extract hour and month
df4$Hour <- hour(df4$Date)
df4$Month <- month(df4$Date)

# View result
str(df4)

# save cleaned data set to csv
#write.csv(df4, "df_pca.csv", row.names = FALSE)
```

#### Load in data

```{r}
set.seed(123)
# load in data
df <- read.csv("df_pca.csv")
# Sample 2000 rows randomly
# df <- df[sample(nrow(df), 10000), ]
```

```{r}
# save labels in a separate variable and remove from data set
label <- df$Arrest
df$Arrest <- NULL
df$Date <- NULL
str(df)
```

```{r}
# scale all column values
df_sc <- as.data.frame(scale(df))
summary(df_sc)
```

## PCA

```{r}
data.pca <- princomp(df_sc)
summary(data.pca)
```

```{r}
data.pca$loadings[, 1:4]
```

```{r}
# scree plot
fviz_eig(data.pca, addlabels = TRUE)
```

```{r}
# Biplot of the attributes
# Graph of the variables
fviz_pca_var(data.pca, col.var = "black")
```

```{r}
# Contribution of each variable 
fviz_cos2(data.pca, choice = "var", axes = 1:4)

```

```{r}
# Biplot combined with cos2 
fviz_pca_var(data.pca, col.var = "cos2",
            gradient.cols = c("black", "orange", "green"),
            repel = TRUE)
```

